"""
SKU generation utilities for autogenerated product identifiers.
Format: PRD-XXXXXX where X is alphanumeric (excluding confusing chars).
"""
import secrets
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models import Product
from fastapi import HTTPException

# Character set excluding confusing characters (I, O, 1, 0)
SKU_CHARSET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
SKU_PREFIX = "PRD"
SKU_LENGTH = 6
MAX_GENERATION_ATTEMPTS = 5


def generate_random_sku() -> str:
    """
    Generate a random SKU in format PRD-XXXXXX.

    Returns:
        str: Generated SKU (e.g., "PRD-K8M3N7")
    """
    random_part = ''.join(secrets.choice(SKU_CHARSET) for _ in range(SKU_LENGTH))
    return f"{SKU_PREFIX}-{random_part}"


async def generate_unique_sku(tenant_id: int, db: AsyncSession) -> str:
    """
    Generate a unique SKU for a tenant, with collision retry logic.

    Args:
        tenant_id: Tenant ID to ensure tenant-scoped uniqueness
        db: Database session for uniqueness checks

    Returns:
        str: Unique SKU for the tenant

    Raises:
        HTTPException: If unable to generate unique SKU after MAX_GENERATION_ATTEMPTS
    """
    for attempt in range(MAX_GENERATION_ATTEMPTS):
        sku = generate_random_sku()

        # Check if SKU exists for this tenant
        result = await db.execute(
            select(Product).where(
                Product.tenant_id == tenant_id,
                Product.sku == sku
            )
        )
        existing_product = result.scalar_one_or_none()

        if not existing_product:
            if attempt > 0:
                # Log collision (rare event worth monitoring)
                print(f"SKU collision detected on attempt {attempt + 1} for tenant {tenant_id}: {sku}")
            return sku

    # Extremely unlikely to reach here (probability < 10^-50)
    raise HTTPException(
        status_code=500,
        detail=f"Failed to generate unique SKU after {MAX_GENERATION_ATTEMPTS} attempts. Please try again."
    )
